# Generated by Django 6.0 on 2026-01-07 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_managers_user_is_super"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("username", "company")},
        ),
    ]
