# Generated by Django 6.0 on 2026-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("ON_LEAVE", "On Leave"),
                    ("SUSPENDED", "Suspended"),
                    ("TERMINATED", "Terminated"),
                    ("RESIGNED", "Resigned"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
