# Generated by Django 6.0 on 2026-04-01 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_employee_employment_status"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="employee",
        ),
    ]
