# Generated by Django 6.0 on 2026-01-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0003_department_deleted_at_department_deleted_by_and_more"),
        ("users", "0004_alter_user_managers_user_is_super"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designations",
                to="department.department",
            ),
        ),
    ]
