# Generated by Django 6.0 on 2026-01-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holidays", "0001_initial"),
        ("users", "0005_alter_user_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch associated with this holiday",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="users.branch",
            ),
        ),
    ]
