# Generated by Django 6.0 on 2026-01-07 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0005_alter_user_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in",
                    models.DateTimeField(
                        blank=True, help_text="Check-in time of the employee", null=True
                    ),
                ),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True,
                        help_text="Check-out time of the employee",
                        null=True,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the attendance record")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("ON_LEAVE", "On Leave"),
                            ("WORK_FROM_HOME", "Work From Home"),
                        ],
                        default="PRESENT",
                        help_text="Attendance status of the employee",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key referencing the user who created the record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key referencing the user who deleted the record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="users.employee",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key referencing the user who restored the record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_restored_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key referencing the user who updated the record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "db_table": "attendance",
            },
        ),
        migrations.CreateModel(
            name="FingerprintScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("IN", "Check In"), ("OUT", "Check Out")],
                        max_length=10,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "scan_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAIL", "Fail"),
                            ("DUPLICATE", "Duplicate"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fingerprint_scans",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fingerprint_scans",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fingerprint Scan",
                "verbose_name_plural": "Fingerprint Scans",
                "db_table": "fingerprint_scan",
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_scan",
            field=models.ForeignKey(
                blank=True,
                help_text="Fingerprint scan record for check-in",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_checkin",
                to="attendance.fingerprintscan",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_scan",
            field=models.ForeignKey(
                blank=True,
                help_text="Fingerprint scan record for check-out",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_checkout",
                to="attendance.fingerprintscan",
            ),
        ),
    ]
