# Generated by Django 6.0 on 2026-09-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        ("users", "0008_alter_employee_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
        migrations.AddField(
            model_name="attendance",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the attendance was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager who approved this attendance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the attendance has been approved by manager",
            ),
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="check_in_scan",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="check_out_scan",
        ),
        migrations.DeleteModel(
            name="FingerprintScan",
        ),
    ]
